/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorPurchaseOrdersRouteImport } from './routes/vendor.purchase-orders'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorPaymentsRouteImport } from './routes/vendor.payments'
import { Route as VendorMessagesRouteImport } from './routes/vendor.messages'
import { Route as VendorInvoicesRouteImport } from './routes/vendor.invoices'
import { Route as VendorDocumentsRouteImport } from './routes/vendor.documents'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorPurchaseOrdersRoute = VendorPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorPaymentsRoute = VendorPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => VendorRoute,
} as any)
const VendorMessagesRoute = VendorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => VendorRoute,
} as any)
const VendorInvoicesRoute = VendorInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDocumentsRoute = VendorDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => VendorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/invoices': typeof InvoicesRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor': typeof VendorRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/invoices': typeof VendorInvoicesRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/payments': typeof VendorPaymentsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/purchase-orders': typeof VendorPurchaseOrdersRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/invoices': typeof InvoicesRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendors': typeof VendorsRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/invoices': typeof VendorInvoicesRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/payments': typeof VendorPaymentsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/purchase-orders': typeof VendorPurchaseOrdersRoute
  '/vendor': typeof VendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/invoices': typeof InvoicesRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendor': typeof VendorRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/invoices': typeof VendorInvoicesRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/payments': typeof VendorPaymentsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/purchase-orders': typeof VendorPurchaseOrdersRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/invoices'
    | '/messages'
    | '/payments'
    | '/purchase-orders'
    | '/settings'
    | '/sitemap.xml'
    | '/vendor'
    | '/vendors'
    | '/vendor/documents'
    | '/vendor/invoices'
    | '/vendor/messages'
    | '/vendor/payments'
    | '/vendor/profile'
    | '/vendor/purchase-orders'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/invoices'
    | '/messages'
    | '/payments'
    | '/purchase-orders'
    | '/settings'
    | '/sitemap.xml'
    | '/vendors'
    | '/vendor/documents'
    | '/vendor/invoices'
    | '/vendor/messages'
    | '/vendor/payments'
    | '/vendor/profile'
    | '/vendor/purchase-orders'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/documents'
    | '/invoices'
    | '/messages'
    | '/payments'
    | '/purchase-orders'
    | '/settings'
    | '/sitemap.xml'
    | '/vendor'
    | '/vendors'
    | '/vendor/documents'
    | '/vendor/invoices'
    | '/vendor/messages'
    | '/vendor/payments'
    | '/vendor/profile'
    | '/vendor/purchase-orders'
    | '/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  InvoicesRoute: typeof InvoicesRoute
  MessagesRoute: typeof MessagesRoute
  PaymentsRoute: typeof PaymentsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendorRoute: typeof VendorRouteWithChildren
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/purchase-orders': {
      id: '/vendor/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/vendor/purchase-orders'
      preLoaderRoute: typeof VendorPurchaseOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/payments': {
      id: '/vendor/payments'
      path: '/payments'
      fullPath: '/vendor/payments'
      preLoaderRoute: typeof VendorPaymentsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/messages': {
      id: '/vendor/messages'
      path: '/messages'
      fullPath: '/vendor/messages'
      preLoaderRoute: typeof VendorMessagesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/invoices': {
      id: '/vendor/invoices'
      path: '/invoices'
      fullPath: '/vendor/invoices'
      preLoaderRoute: typeof VendorInvoicesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/documents': {
      id: '/vendor/documents'
      path: '/documents'
      fullPath: '/vendor/documents'
      preLoaderRoute: typeof VendorDocumentsRouteImport
      parentRoute: typeof VendorRoute
    }
  }
}

interface VendorRouteChildren {
  VendorDocumentsRoute: typeof VendorDocumentsRoute
  VendorInvoicesRoute: typeof VendorInvoicesRoute
  VendorMessagesRoute: typeof VendorMessagesRoute
  VendorPaymentsRoute: typeof VendorPaymentsRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorPurchaseOrdersRoute: typeof VendorPurchaseOrdersRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorDocumentsRoute: VendorDocumentsRoute,
  VendorInvoicesRoute: VendorInvoicesRoute,
  VendorMessagesRoute: VendorMessagesRoute,
  VendorPaymentsRoute: VendorPaymentsRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorPurchaseOrdersRoute: VendorPurchaseOrdersRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  InvoicesRoute: InvoicesRoute,
  MessagesRoute: MessagesRoute,
  PaymentsRoute: PaymentsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendorRoute: VendorRouteWithChildren,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
